Repository TorchDSP/torchsig, pull requests merged in 2023-05, with the labels that each got.

#72 Fixing wideband generation notebook.
  examples/03_example_widebandsig53_dataset.ipynb
  torchsig/datasets/synthetic.py
Labels: bug

#73 Making suggested fix to example for device consistency.
  examples/02_example_sig53_classifier.py
Labels: bug

#78 Restoring DETR. Notebook runs in QA environment.
  .gitignore
  examples/04_example_wideband_modulations_dataset.ipynb
  examples/05_example_wideband_detector.ipynb
  torchsig/datasets/synthetic.py
  torchsig/datasets/wideband_sig53.py
  torchsig/models/spectrogram_models/__init__.py
  torchsig/models/spectrogram_models/detr/LICENSE.md
  torchsig/models/spectrogram_models/detr/README.md
  torchsig/models/spectrogram_models/detr/__init__.py
  torchsig/models/spectrogram_models/detr/detr.py
  torchsig/models/spectrogram_models/detr/modules.py
  torchsig/models/spectrogram_models/detr/utils.py
Labels: bug

#79 66 review randomized pulse shaping for fsk-msk
  torchsig/datasets/synthetic.py
Labels: enhancement

#86 Initial removal of cupy as dependency. Replaced with torch.
  examples/03_example_widebandsig53_dataset.ipynb
  examples/05_example_wideband_detector.ipynb
  examples/05_example_wideband_detector.py
  examples/06_torch_vs_numpy_convolution.ipynb
  pyproject.toml
  tests/test_writer.py
  torchsig/datasets/modulations.py
  torchsig/datasets/synthetic.py
  torchsig/datasets/wideband.py
  torchsig/models/spectrogram_models/detr/modules.py
  torchsig/models/spectrogram_models/detr/utils.py
  torchsig/utils/writer.py
Labels: enhancement

#89 Keeping folder to avoid crashes.
  examples/sig53/.gitkeep
Labels: bug

#90 Moving estimate_filter_length into datasets module
  torchsig/datasets/__init__.py
  torchsig/datasets/synthetic.py
  torchsig/datasets/wideband.py
Labels: enhancement

#95 Change README logo if in dark mode
  README.md
  docs/torchsig_logo_white_dodgerblue.png
Labels: documentation

#99 OFDM Modulator filter lengths estimated and bandwidth randomized
  torchsig/datasets/synthetic.py
Labels: bug

#105 75 examine ofdm generation for potential speedups for sig53
  torchsig/datasets/synthetic.py
Labels: enhancement

#108 74 create a baseline dockerfile to demonstrate installation
  Dockerfile
  README.md
  pyproject.toml
Labels: documentation

#115 45 consider compatibility with torch 20
  .github/workflows/pip_build.yml
  .github/workflows/pytest.yml
  pyproject.toml
Labels: enhancement

#119 Migrated to pytest.
  tests/test_datasets_sig53.py
  tests/test_transforms.py
  tests/test_wideband_figures.py
  tests/test_writer.py
Labels: documentation

#120 Added model instantiation tests for narrowband signals.
  tests/test_models.py
Labels: enhancement

#121 85 gmskgfsk also needs faster filtering due to convolution of long signals with gaussian pulse shape
  torchsig/datasets/synthetic.py
  torchsig/datasets/wideband.py
  torchsig/transforms/functional.py
Labels: enhancement
